# Generated by Django 5.0 on 2024-02-07 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='boards.post')),
                ('accepting_points', models.PositiveSmallIntegerField()),
                ('accepted_at', models.DateTimeField(default=None, null=True)),
                ('accepted_comment', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.comment')),
            ],
        ),
    ]
