# Generated by Django 5.0 on 2024-01-23 10:57

from django.db import migrations


def create_base_role(apps, schema_editor):
    Role = apps.get_model("role", "Role")
    Role.objects.create(id="0000000000001", name="Base Role", description="This is a base role")


def create_base_role_reverse(apps, schema_editor):
    Role = apps.get_model("role", "Role")
    Role.objects.get(id="0000000000001").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("role", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_base_role, create_base_role_reverse),
    ]
