# Generated by Django 5.0 on 2024-01-21 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointhistory',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='pointhistory',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]