# Generated by Django 5.0 on 2024-02-02 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_remove_applicant_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='recruit',
        ),
    ]
