# Generated by Django 5.0 on 2024-02-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0004_remove_applicant_recruit'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_team',
            field=models.BooleanField(default=False),
        ),
    ]
