# Generated by Django 5.0 on 2024-02-09 04:27

import tsid_pk.fields
import tsid_pk.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0005_event_is_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='id',
            field=tsid_pk.fields.TSIDField(db_index=True, default=tsid_pk.utils.generate_tsid, max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='id',
            field=tsid_pk.fields.TSIDField(db_index=True, default=tsid_pk.utils.generate_tsid, max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=tsid_pk.fields.TSIDField(db_index=True, default=tsid_pk.utils.generate_tsid, max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='id',
            field=tsid_pk.fields.TSIDField(db_index=True, default=tsid_pk.utils.generate_tsid, max_length=13, primary_key=True, serialize=False),
        ),
    ]
