# Generated by Django 5.0 on 2024-02-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0006_alter_applicant_id_alter_calendar_id_alter_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
