# Generated by Django 5.0 on 2024-02-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0008_event_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='note',
            field=models.CharField(default='', max_length=255),
        ),
    ]
