# Generated by Django 5.0 on 2024-02-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0009_recruit_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
