# Generated by Django 5.0 on 2024-02-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0010_event_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
