# Generated by Django 5.0 on 2024-02-09 04:27

import tsid_pk.fields
import tsid_pk.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_award_is_hidden_bounty_is_hidden_challenge_is_hidden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='id',
            field=tsid_pk.fields.TSIDField(db_index=True, default=tsid_pk.utils.generate_tsid, max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='id',
            field=tsid_pk.fields.TSIDField(db_index=True, default=tsid_pk.utils.generate_tsid, max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='id',
            field=tsid_pk.fields.TSIDField(db_index=True, default=tsid_pk.utils.generate_tsid, max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='education',
            name='id',
            field=tsid_pk.fields.TSIDField(db_index=True, default=tsid_pk.utils.generate_tsid, max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='experience',
            name='id',
            field=tsid_pk.fields.TSIDField(db_index=True, default=tsid_pk.utils.generate_tsid, max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='experienceskill',
            name='id',
            field=tsid_pk.fields.TSIDField(db_index=True, default=tsid_pk.utils.generate_tsid, max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='id',
            field=tsid_pk.fields.TSIDField(db_index=True, default=tsid_pk.utils.generate_tsid, max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profilelink',
            name='id',
            field=tsid_pk.fields.TSIDField(db_index=True, default=tsid_pk.utils.generate_tsid, max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profileskill',
            name='id',
            field=tsid_pk.fields.TSIDField(db_index=True, default=tsid_pk.utils.generate_tsid, max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=tsid_pk.fields.TSIDField(db_index=True, default=tsid_pk.utils.generate_tsid, max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=tsid_pk.fields.TSIDField(db_index=True, default=tsid_pk.utils.generate_tsid, max_length=13, primary_key=True, serialize=False),
        ),
    ]
