# Generated by Django 5.0 on 2024-02-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_alter_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bounty',
            name='cvss',
        ),
        migrations.AddField(
            model_name='bounty',
            name='score',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
