# Generated by Django 5.0 on 2024-02-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_remove_bounty_cvss_bounty_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
