# Generated by Django 5.0 on 2024-02-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_alter_banner_description_alter_banner_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
