# Generated by Django 5.0 on 2024-02-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigations', '0002_alter_navigation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
