# Generated by Django 5.0 on 2024-02-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailuser', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
