# Generated by Django 5.0 on 2024-02-09 04:27

import tsid_pk.fields
import tsid_pk.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='board',
            name='id',
            field=tsid_pk.fields.TSIDField(db_index=True, default=tsid_pk.utils.generate_tsid, max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=tsid_pk.fields.TSIDField(db_index=True, default=tsid_pk.utils.generate_tsid, max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=tsid_pk.fields.TSIDField(db_index=True, default=tsid_pk.utils.generate_tsid, max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_object_id',
            field=tsid_pk.fields.TSIDField(db_index=True, default=tsid_pk.utils.generate_tsid, max_length=13),
        ),
        migrations.AlterField(
            model_name='comment',
            name='root_object_id',
            field=tsid_pk.fields.TSIDField(db_index=True, default=tsid_pk.utils.generate_tsid, max_length=13),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=tsid_pk.fields.TSIDField(db_index=True, default=tsid_pk.utils.generate_tsid, max_length=13, primary_key=True, serialize=False),
        ),
    ]
