# Generated by Django 5.0 on 2024-02-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
