# Generated by Django 5.0 on 2024-02-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_board_deleted_at_category_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
